# ASCII Text Art: http://patorjk.com/software/taag/#p=display&f=Slant&t=chendaniely

# Site Info
title: Emmanuel Castillo
tagline: '"Save the cheerleader, save the world"'
description: 'A Jekyll theme adapted from <a href="https://github.com/chendaniely/chendaniely.github.io" target="_blank">chendaniely </a> <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'

#baseurl: ""
url: http://forcesk.github.io
#logo: '/public/dc/dc-69.png'
logo: '/public/dc/image.png'

# Site configurations
gems:
  - jekyll-paginate
  - jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 10
paginate_path: '/blog/page:num'
permalink: pretty

collections:
  data_science:
    output: true

jupyter_notebooks: /notebooks/

version: 0.3.2

# About/contact
author:
  name: Emmanuel Castillo G.
  description: Biology, Computacional Sciences, Machine Learning, Deep Learning, <strong>Bioinformatics</strong>.
  gravatar: f67902456f1aa69f9b938353391b5069

  contact:
    #linkedin:  
    github:    https://github.com/forcesk
    # facebook:  <hide>
    twitter:   https://twitter.com/iEmmCastillo_
    #instagram: 
    #lastfm: 
    # weibo:     
     #email: Emm.castillog@gmail.com     
    #orcid:     

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  Projects:
    #- /projects/
  #Talks:
    #- /talks/
  #Research:
    #- /research/
#   Teaching:
#     - '/teaching/'
  Data Science:
#     - /data_science/
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# Puglins
mathjax: true # whether support mathjax
#google_analytics_token: ' ' # leave blank if you don't want google analytics
disqus_short_name: 'forces' # leave blank if you don't want disqus

hero:
  image: '/public/CDMX.jpg'
  caption: Do. Or do not. There is no try.                                         <strong> Emmanuel Castillo G. </strong>
  #caption: Original Artwork &copy; <a href="http://science.sciencemag.org/content/358/6370/1530.full">Science Magazine, Vol. 358, Issue 6370, pp. 1530-1534</a>

# image: http://imgs.xkcd.com/comics/frequentists_vs_bayesians.png
# caption: Original Artwork &copy; <a href="https://xkcd.com/1831/">XKCD - Randall Munroe</a>

project_logos:
  #safari_books_online: /public/project_images/safari-logo-lockup-sunshine.png
  #datacamp: /public/project_images/datacamp_white_fulllogo_tagline.png
  #pandas_for_everyone: /public/project_images/pandas_for_everyone.jpg
  #github_octocat: /public/project_images/octocat/Octocat.png

#               __    
#   __  _______/ /____
#  / / / / ___/ / ___/
# / /_/ / /  / (__  ) 
# \__,_/_/  /_/____/  
#

dc                                   : "http://datacarpentry.org"
swc                                  : "https://v4.software-carpentry.org"
r-novice                             : "http://swcarpentry.github.io/r-novice-inflammation/"

bi                                   : "https://www.bi.vt.edu/"
sdal                                 : "https://www.bi.vt.edu/sdal"
ndssl                                : "https://www.bi.vt.edu/ndssl"
gbcb                                 : "http://gbcb.vbi.vt.edu/"

cu_mph                               : "https://www.mailman.columbia.edu/become-student/degrees/masters-programs/masters-public-health/columbia-mph"
cu_epi                               : "https://www.mailman.columbia.edu/become-student/departments/epidemiology"
cu_adv_epi                           : "https://www.mailman.columbia.edu/become-student/degrees/masters-programs/masters-public-health/columbia-mph/certificates/advanced"

macaulay                             : "https://macaulay.cuny.edu/"
hunter                               : "http://www.hunter.cuny.edu/main/"
cuny                                 : "http://www2.cuny.edu/"

stuy                                 : "http://stuy.enschool.org/"

mark_orr                             : "http://mark-orr.github.io/"
kaja_abbas                           : "http://www.kajaabbas.com/"
jacqueline_merrill_1                 : "http://www.columbia.edu/~jam119/"
jacqueline_merrill_2                 : "http://nursing.columbia.edu/profile/jmerrill"
aaron_schroeder                      : "http://dads2busy.github.io/"

lander_analytics                     : "https://www.landeranalytics.com/"

aur                                  : "https://www.archlinux.org/"
rstudio-desktop-preview-bin          : "https://aur.archlinux.org/packages/rstudio-desktop-preview-bin/"
rodeo                                : "https://aur.archlinux.org/packages/rodeo/"

mann                                 : "https://github.com/chendaniely/mann"
mann_code                            : "https://github.com/chendaniely/multi-agent-neural-network"
mann2_code                           : "https://github.com/chendaniely/mann2"

mann_sims                            : "https://github.com/chendaniely/multidisciplinary-diffusion-model-experiments"
mann2_sims                           : "https://github.com/chendaniely/mann2_simulations"

mann_assortativity                   : "https://github.com/chendaniely/mann_assortativity_analysis"
mann2_analysis                       : "https://github.com/chendaniely/mann2_analysis"
mannAnalysisR                        : "https://github.com/chendaniely/mannAnalysisR"

#                      __                __      
#     ____  ____  ____/ /________ ______/ /______
#    / __ \/ __ \/ __  / ___/ __ `/ ___/ __/ ___/
#   / /_/ / /_/ / /_/ / /__/ /_/ (__  ) /_(__  ) 
#  / .___/\____/\__,_/\___/\__,_/____/\__/____/  
# /_/                                            
#

#podcasts:
#- name: Not So Standard Deviations
  #image: /public/podcasts/not_so_standard_deviations-500x500.jpg
  #url: https://soundcloud.com/nssd-podcast

#podcast_settings:
 # global_size_width: 100px
 # global_size_height: 100px
